# resources/DTDS_AuditPolicy/DTDS_AuditPolicy.psm1
#
# Class-based DSC resource: DTDS_AuditPolicy
#
# Manages Windows Security Audit Policy settings using `auditpol.exe`.
# Relevant for DORA Art.10 (log integrity / audit trail) and NIS2 Art.21(2)(b).
#
# Documentation for this resource is auto-generated by DscResource.DocGenerator:
#   pwsh -File dsc/build.ps1
#
# Related ADR:          docs/adrs/0011-dora-compliance.md
# Related requirements: DORA-002, NIS2-004, S-008

<#
.SYNOPSIS
    Audit policy success/failure tracking value.

.DESCRIPTION
    Controls whether an audit policy subcategory tracks Success events,
    Failure events, both, or neither.
#>
enum AuditTracking {
    NoAuditing
    Success
    Failure
    SuccessAndFailure
}

<#
.SYNOPSIS
    Manages a Windows Security Audit Policy subcategory.

.DESCRIPTION
    The DTDS_AuditPolicy resource configures a Windows Security Audit Policy
    subcategory via `auditpol.exe`.  It is used to ensure that the required
    events are logged for DORA (EU 2022/2554) Art.10 compliance and CIS
    Benchmark Section 17.

    On Linux/macOS the resource always reports the desired state as satisfied
    (no-op) because audit policies are managed via auditd rules rather than
    `auditpol`.

.NOTES
    Tags:   Audit, Security, DORA, NIS2, Windows
    Author: platform-team
#>
[DscResource()]
class DTDS_AuditPolicy {

    <#
    .PARAMETER Subcategory
        The Windows audit policy subcategory name as shown by `auditpol /list /subcategory:*`.
        Examples: 'Logon', 'Account Lockout', 'Process Creation', 'Policy Change'.
        Acts as the key property.

    .EXAMPLE
        Subcategory = 'Logon'

    .EXAMPLE
        Subcategory = 'Process Creation'
    #>
    [DscProperty(Key)]
    [string] $Subcategory

    <#
    .PARAMETER AuditFlag
        Which events to audit for this subcategory.
        Allowed values: NoAuditing, Success, Failure, SuccessAndFailure.

    .EXAMPLE
        AuditFlag = [AuditTracking]::SuccessAndFailure
    #>
    [DscProperty(Mandatory)]
    [AuditTracking] $AuditFlag

    # ------------------------------------------------------------------
    # DSC methods
    # ------------------------------------------------------------------

    <#
    .SYNOPSIS Sets the audit policy subcategory to the desired tracking level.
    #>
    [void] Set() {
        if (-not $this._IsWindows()) {
            Write-Verbose "DTDS_AuditPolicy: Not Windows — skipping auditpol configuration."
            return
        }
        $flagStr = $this._AuditFlagToString($this.AuditFlag)
        $successFlag = if ($this.AuditFlag -eq [AuditTracking]::Success -or $this.AuditFlag -eq [AuditTracking]::SuccessAndFailure) { "enable" } else { "disable" }
        $failureFlag = if ($this.AuditFlag -eq [AuditTracking]::Failure -or $this.AuditFlag -eq [AuditTracking]::SuccessAndFailure) { "enable" } else { "disable" }
        Write-Verbose "DTDS_AuditPolicy: Setting '$($this.Subcategory)' to '$flagStr'"
        $result = auditpol /set /subcategory:"$($this.Subcategory)" /success:$successFlag /failure:$failureFlag 2>&1
        if ($LASTEXITCODE -ne 0) {
            throw "auditpol failed for subcategory '$($this.Subcategory)': $result"
        }
    }

    <#
    .SYNOPSIS Tests whether the audit policy subcategory matches the desired state.
    .OUTPUTS [bool] True if already in desired state.
    #>
    [bool] Test() {
        if (-not $this._IsWindows()) {
            # On Linux/macOS, treat as always satisfied
            return $true
        }
        $current = $this._GetCurrentAuditFlag()
        return ($current -eq $this.AuditFlag)
    }

    <#
    .SYNOPSIS Returns the current state of the audit policy subcategory.
    .OUTPUTS [DTDS_AuditPolicy]
    #>
    [DTDS_AuditPolicy] Get() {
        $result = [DTDS_AuditPolicy]::new()
        $result.Subcategory = $this.Subcategory
        if (-not $this._IsWindows()) {
            $result.AuditFlag = $this.AuditFlag
        } else {
            $result.AuditFlag = $this._GetCurrentAuditFlag()
        }
        return $result
    }

    # ------------------------------------------------------------------
    # Private helpers
    # ------------------------------------------------------------------

    hidden [bool] _IsWindows() {
        return ($PSVersionTable.Platform -eq 'Win32NT' -or $IsWindows -eq $true -or $env:OS -eq 'Windows_NT')
    }

    hidden [AuditTracking] _GetCurrentAuditFlag() {
        $output = auditpol /get /subcategory:"$($this.Subcategory)" 2>&1 | Out-String
        $success = $output -match 'Success'
        $failure = $output -match 'Failure'
        if ($success -and $failure) { return [AuditTracking]::SuccessAndFailure }
        if ($success)               { return [AuditTracking]::Success }
        if ($failure)               { return [AuditTracking]::Failure }
        return [AuditTracking]::NoAuditing
    }

    hidden [string] _AuditFlagToString([AuditTracking] $flag) {
        return $flag.ToString()
    }
}
