# dsc/build.ps1
#
# Generates Markdown documentation for all DSC resources in ./resources/
# using DscResource.DocGenerator + PlatyPS.
#
# The generated Markdown is written to ../docs/generated/dsc-resources/
# and is included in the MkDocs site via the "Generated" nav section.
#
# Usage — local (requires DscResource.DocGenerator):
#   Install-Module -Name DscResource.DocGenerator, PlatyPS -Force
#   pwsh -File dsc/build.ps1
#
# Usage — CI:
#   The docs-build job in .github/workflows/docs-pipeline.yml runs this script
#   automatically after installing the required modules.

[CmdletBinding()]
param(
    [string] $OutputPath = (Join-Path $PSScriptRoot '../docs/generated/dsc-resources')
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

Write-Host '=== DSC Resource Documentation Generator ===' -ForegroundColor Cyan

# Ensure the output directory exists
$null = New-Item -ItemType Directory -Path $OutputPath -Force
Write-Host "Output directory: $OutputPath"

$resourcesRoot = Join-Path $PSScriptRoot 'resources'
$anyFailure    = $false

foreach ($moduleDir in Get-ChildItem -Path $resourcesRoot -Directory) {

    Write-Host "`nProcessing: $($moduleDir.Name)" -ForegroundColor Yellow

    $psmFile = Join-Path $moduleDir.FullName "$($moduleDir.Name).psm1"
    $psdFile = Join-Path $moduleDir.FullName "$($moduleDir.Name).psd1"

    if (-not (Test-Path $psmFile)) {
        Write-Warning "  Skipping — no .psm1 found at $psmFile"
        continue
    }

    # Import the module so DscResource.DocGenerator can reflect on the class
    Import-Module $psmFile -Force -ErrorAction SilentlyContinue

    $docGenAvailable = Get-Command 'New-DscResourceWikiPage' -ErrorAction SilentlyContinue

    if ($docGenAvailable) {
        try {
            # Generate one Markdown wiki page per exported DSC resource
            New-DscResourceWikiPage `
                -SourcePath     $moduleDir.FullName `
                -DestinationPath $OutputPath `
                -Force `
                -Verbose:$false

            Write-Host "  OK  Documentation generated for $($moduleDir.Name)" -ForegroundColor Green
        }
        catch {
            Write-Warning "  DscResource.DocGenerator failed: $_"
            $anyFailure = $true
            # Fall through to stub generation below
            $docGenAvailable = $null
        }
    }

    if (-not $docGenAvailable) {
        # Fallback: emit a stub page so MkDocs can still build in CI
        # environments where DscResource.DocGenerator is not installed.
        Write-Warning "  Generating stub page for $($moduleDir.Name)"

        $rawSource = Get-Content -Path $psmFile -Raw -Encoding UTF8
        $outFile   = Join-Path $OutputPath "$($moduleDir.Name).md"

        # Extract the SYNOPSIS from the class-level comment block
        $synopsisMatch = [regex]::Match($rawSource, '\.SYNOPSIS\s*\n\s*(.+)')
        $synopsis = if ($synopsisMatch.Success) { $synopsisMatch.Groups[1].Value.Trim() } else { 'See source file.' }

        @"
# $($moduleDir.Name)

!!! note "Generated documentation"
    This page is generated by ``DscResource.DocGenerator`` during the CI/CD
    pipeline.  Install ``DscResource.DocGenerator`` locally and run
    ``pwsh -File dsc/build.ps1`` to regenerate.

**Module:** ``$($moduleDir.Name)``  
**Version:** $(if (Test-Path $psdFile) { (Import-PowerShellDataFile $psdFile).ModuleVersion } else { 'unknown' })  
**Synopsis:** $synopsis

## Source

``````powershell
$rawSource
``````
"@ | Set-Content -Path $outFile -Encoding UTF8

        Write-Host "  STUB  Stub page written to $outFile" -ForegroundColor DarkYellow
    }
}

if ($anyFailure) {
    Write-Warning "`nOne or more resources used stub generation.  Install DscResource.DocGenerator for full output:"
    Write-Warning "  Install-Module -Name DscResource.DocGenerator, PlatyPS -Force"
}
else {
    Write-Host "`nAll DSC resource documentation generated successfully." -ForegroundColor Green
}

Write-Host "Documentation written to: $OutputPath" -ForegroundColor Cyan
