# main.tf — Example infrastructure module using the `local` provider.
#
# Purpose: showcase deterministic documentation generation without requiring
# real cloud credentials.  The `local` provider writes configuration artefacts
# to the working directory the same way a real provider would create cloud
# resources, so every terraform-docs, OPA, and MkDocs step works identically.

terraform {
  required_version = ">= 1.5.0"

  required_providers {
    local = {
      source  = "hashicorp/local"
      version = "~> 2.5"
    }
  }
}

# ---------------------------------------------------------------------------
# Locals — cost-allocation tags (FinOps as Code)
# ---------------------------------------------------------------------------

locals {
  common_tags = {
    environment = var.environment
    app_name    = var.app_name
    owner       = var.owner
    cost_center = var.cost_center
    managed_by  = "terraform"
  }

  # Rendered JSON that a real provider would attach as resource tags.
  tags_json = jsonencode(local.common_tags)
}

# ---------------------------------------------------------------------------
# Application configuration file
# ---------------------------------------------------------------------------

resource "local_file" "app_config" {
  filename = "${path.module}/output/app-config.json"
  content = jsonencode({
    app_name       = var.app_name
    environment    = var.environment
    replica_count  = var.replica_count
    enable_backups = var.enable_backups
    tags           = local.common_tags
  })
  file_permission = "0644"
}

# ---------------------------------------------------------------------------
# Deployment manifest
# ---------------------------------------------------------------------------

resource "local_file" "deployment_manifest" {
  filename = "${path.module}/output/deployment-manifest.yaml"
  content  = <<-YAML
    # Auto-generated by Terraform — do not edit manually.
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: ${var.app_name}
      labels:
        environment: ${var.environment}
        owner: ${var.owner}
        cost_center: ${var.cost_center}
        managed_by: terraform
    spec:
      replicas: ${var.replica_count}
      selector:
        matchLabels:
          app: ${var.app_name}
      template:
        metadata:
          labels:
            app: ${var.app_name}
            environment: ${var.environment}
        spec:
          containers:
            - name: ${var.app_name}
              image: nginx:stable
              ports:
                - containerPort: 80
  YAML
  file_permission = "0644"
}
