# resources/DTDS_FirewallRule/DTDS_FirewallRule.psm1
#
# Class-based DSC resource: DTDS_FirewallRule
#
# Manages Windows Defender Firewall rules using `netsh advfirewall`.
# Relevant for network hardening (SEC-004, CYB-004) and DORA Art.9.
#
# Documentation for this resource is auto-generated by DscResource.DocGenerator:
#   pwsh -File dsc/build.ps1
#
# Related ADR:          docs/adrs/0002-use-opa-for-policy.md
#                       docs/adrs/0011-dora-compliance.md
# Related requirements: CYB-004, SEC-004, DORA-001, S-008

<#
.SYNOPSIS
    Firewall rule direction.
#>
enum FirewallDirection {
    Inbound
    Outbound
}

<#
.SYNOPSIS
    Firewall rule action.
#>
enum FirewallAction {
    Allow
    Block
}

<#
.SYNOPSIS
    Whether the firewall rule should be Present (default) or Absent.
#>
enum FirewallEnsure {
    Present
    Absent
}

<#
.SYNOPSIS
    Manages a Windows Defender Firewall rule.

.DESCRIPTION
    The DTDS_FirewallRule resource creates, updates, or removes a named Windows
    Defender Firewall rule using `netsh advfirewall firewall`.

    On Linux/macOS the resource always reports the desired state as satisfied
    (no-op) — firewall rules on Linux are managed via iptables/nftables through
    the Ansible `security_baseline` role.

    This resource is used to implement CIS Benchmark network hardening controls
    and to satisfy DORA Art.9 (network-level access control evidence).

.NOTES
    Tags:   Firewall, Network, Security, DORA, NIS2, Windows
    Author: platform-team
#>
[DscResource()]
class DTDS_FirewallRule {

    <#
    .PARAMETER RuleName
        The unique display name of the firewall rule.
        Acts as the key property.

    .EXAMPLE
        RuleName = 'Block-RDP-Inbound'

    .EXAMPLE
        RuleName = 'Allow-HTTPS-Outbound'
    #>
    [DscProperty(Key)]
    [string] $RuleName

    <#
    .PARAMETER Direction
        Whether this rule applies to inbound or outbound traffic.

    .EXAMPLE
        Direction = [FirewallDirection]::Inbound
    #>
    [DscProperty(Mandatory)]
    [FirewallDirection] $Direction

    <#
    .PARAMETER Protocol
        The IP protocol: TCP, UDP, or Any.

    .EXAMPLE
        Protocol = 'TCP'
    #>
    [DscProperty(Mandatory)]
    [string] $Protocol

    <#
    .PARAMETER LocalPort
        The local port or port range (e.g. '3389', '8080-8090', 'Any').

    .EXAMPLE
        LocalPort = '3389'

    .EXAMPLE
        LocalPort = 'Any'
    #>
    [DscProperty(Mandatory)]
    [string] $LocalPort

    <#
    .PARAMETER Action
        Allow or Block matching traffic.

    .EXAMPLE
        Action = [FirewallAction]::Block
    #>
    [DscProperty(Mandatory)]
    [FirewallAction] $Action

    <#
    .PARAMETER Ensure
        Whether the firewall rule should be Present (default) or Absent.

    .EXAMPLE
        Ensure = [FirewallEnsure]::Present
    #>
    [DscProperty()]
    [FirewallEnsure] $Ensure = [FirewallEnsure]::Present

    <#
    .PARAMETER Description
        Human-readable description of the rule's purpose (for audit traceability).

    .EXAMPLE
        Description = 'Block RDP from internet — CYB-004'
    #>
    [DscProperty()]
    [string] $Description = ''

    # ------------------------------------------------------------------
    # DSC methods
    # ------------------------------------------------------------------

    <#
    .SYNOPSIS Sets the firewall rule to the desired state.
    #>
    [void] Set() {
        if (-not $this._IsWindows()) {
            Write-Verbose "DTDS_FirewallRule: Not Windows — skipping firewall configuration."
            return
        }
        if ($this.Ensure -eq [FirewallEnsure]::Absent) {
            Write-Verbose "DTDS_FirewallRule: Removing rule '$($this.RuleName)'"
            netsh advfirewall firewall delete rule name="$($this.RuleName)" | Out-Null
        } else {
            Write-Verbose "DTDS_FirewallRule: Creating/updating rule '$($this.RuleName)'"
            $dir    = $this.Direction.ToString().ToLower()
            $action = $this.Action.ToString().ToLower()
            $proto  = $this.Protocol.ToLower()
            $port   = $this.LocalPort
            # Delete any existing rule with this name first (idempotent update pattern:
            # netsh has no "update" command; delete+add is the standard approach)
            netsh advfirewall firewall delete rule name="$($this.RuleName)" 2>&1 | Out-Null
            $cmd = "netsh advfirewall firewall add rule name=`"$($this.RuleName)`" dir=$dir action=$action protocol=$proto localport=$port enable=yes"
            if ($this.Description) { $cmd += " description=`"$($this.Description)`"" }
            Invoke-Expression $cmd | Out-Null
            if ($LASTEXITCODE -ne 0) {
                throw "netsh failed to create firewall rule '$($this.RuleName)'"
            }
        }
    }

    <#
    .SYNOPSIS Tests whether the firewall rule matches the desired state.
    .OUTPUTS [bool] True if already in desired state.
    #>
    [bool] Test() {
        if (-not $this._IsWindows()) { return $true }
        $exists = $this._RuleExists()
        if ($this.Ensure -eq [FirewallEnsure]::Absent) { return -not $exists }
        if (-not $exists) { return $false }
        # Verify action and direction match
        $output = netsh advfirewall firewall show rule name="$($this.RuleName)" 2>&1 | Out-String
        $dirOk    = $output -match "Direction:\s+$($this.Direction)"
        $actionOk = $output -match "Action:\s+$($this.Action)"
        return ($dirOk -and $actionOk)
    }

    <#
    .SYNOPSIS Returns the current state of the firewall rule.
    .OUTPUTS [DTDS_FirewallRule]
    #>
    [DTDS_FirewallRule] Get() {
        $result = [DTDS_FirewallRule]::new()
        $result.RuleName  = $this.RuleName
        $result.Direction = $this.Direction
        $result.Protocol  = $this.Protocol
        $result.LocalPort = $this.LocalPort
        $result.Action    = $this.Action
        $result.Description = $this.Description
        if (-not $this._IsWindows()) {
            $result.Ensure = $this.Ensure
        } else {
            $result.Ensure = if ($this._RuleExists()) { [FirewallEnsure]::Present } else { [FirewallEnsure]::Absent }
        }
        return $result
    }

    # ------------------------------------------------------------------
    # Private helpers
    # ------------------------------------------------------------------

    hidden [bool] _IsWindows() {
        return ($PSVersionTable.Platform -eq 'Win32NT' -or $IsWindows -eq $true -or $env:OS -eq 'Windows_NT')
    }

    hidden [bool] _RuleExists() {
        $output = netsh advfirewall firewall show rule name="$($this.RuleName)" 2>&1 | Out-String
        return $output -notmatch 'No rules match the specified criteria'
    }
}
